var students_name = [
  "Adarsh Neekhra",
  "Aditya Kalra",
  "Aman Kant",
  "Amit Mohanpuria",
  "Aneesh Sharma",
  "Anmol Jain",
  "Ansh Tyagi",
  "Anupreet Singh Sidhu",
  "Auchitya Gautam",
  "Ayush Katiar",
  "Ayushi Gupta",
  "Garun Dhwaj Meena",
  "Hanny Singh",
  "Harshit Joshi",
  "Hemant Singh",
  "Hitansh Madan",
  "Nilesh Gupta",
  "Nishant Sabbarwal",
  "Paras Yadav",
  "Pranati Gupta",
  "Pulkit Dhirana",
  "Pulkit Goyal",
  "Rahul Gupta",
  "Rahul Jaglan",
  "Ravi Sehrawat",
  "Rishap Kumar",
  "Sagar Saini",
  "Saksham Khajuria",
  "Samarth Mehra",
  "Shubham Gupta",
  "Shubham Kumar",
  "Shubham Singh",
  "Siddhant Tiwari",
  "Vaibhav Bhaskar",
  "Yash Gupta",
  "Yash Mugdal",
];
